import time

list1 = [] #Que vas a hacer linea 14
print('Te despiertas, estas en tu habitación dormido, está sonando la alarma del telefono. Ves que son las 6:00 AM.')
print()
time.sleep(5)
print('Recuerdas que tienes un exámen de Historia, del cual no estudiastes mucho que digamos. Por eso has madrugado, para intentare aprobarlo.')
print()
time.sleep(7)
print('Escuchas una fuerte explosion...')
print()
time.sleep(3)
print('Te asomas por la ventana para ver que ha ocurrido.')
print()
time.sleep(3)
print('Ves que explotó la central nuclear de Columbus, Ohio.')
print()
time.sleep(4)
print('Cuando se acerca la honda expansiva sientes algo raro en tu mente, pero lo ignoras completamente.')
print()
time.sleep(4)
print('¿Que vas a hacer?')
print('\n\t1.- Avisar a todos tus familiares dentro de tu hogar.\n\t2.- Llamar a emergencias e informar de la situación.\n\t3.- Seguir durmiendo\n\t4.- Te da igual lo que ocurra y te pones a estudiar historia.')
list1=int(input())
if list1==1:
    print('Vas corriendo por todas las habitaciones de la casa. Pegando gritos para que se despierten.')
    print('Despiertas a tus padres y hermano, preguntandote que ocurre.')
    print('Les explicas que ha habido una explosión el la central nuclear.')
    print('Cogeís lo más importante y llamais al número de emergencias para seguir los consejos del gobierno.')
    print('La linea de emergencias esta colapsada, de todas formas haceís lo que a veces dicen que hay que hacer en caso de desastres.')
    print('Cogeís el auto y os vais al chalet que esta alejado de la ciudad. Tiene todas la cosas necesarias para estos casos.')
    print('Entonces estas un poco mareado y recuerdas lo que te pasó cuando la explosión.')
    print('')